export const data = [
  {
    id: "f1",
    name: "Flight 1",
    from: "Place A",
    to: "Place B",
    passengers: [
      {
        name: "Name 1",
        age: "21",
        address: "Street 1",
        passportNo: "1234567890",
        ancillary: "Wheelchair",
        seat: 1,
        checkedIn: true,
        disabled: true,
        infant: false,
      },
      {
        name: "Name 2",
        age: "22",
        address: "Street 2",
        passportNo: "1234567891",
        ancillary: "None",
        seat: 2,
        checkedIn: true,
        disabled: false,
        infant: true,
      },
      {
        name: "Name 3",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 3,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 4",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 4,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 5",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 5,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 6",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 6,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 7",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 7,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 8",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 8,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 9",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 9,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 10",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 10,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 11",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 11,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 12",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 12,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 13",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 13,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 14",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 14,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 15",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 15,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 16",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 16,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 17",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 17,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 18",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 18,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 19",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 19,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 20",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 20,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 21",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 21,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 22",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 22,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 23",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 23,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 24",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 24,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 25",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 25,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 26",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 26,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 27",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 27,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 28",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 28,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 29",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 29,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 30",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 30,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 31",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 31,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 32",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 32,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 33",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 33,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 34",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 34,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 35",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 35,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 36",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 36,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 37",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 37,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 38",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 38,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 39",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 39,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 40",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 40,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
    ],
  },
  {
    id: "f2",
    name: "Flight 2",
    from: "Place C",
    to: "Place D",
    passengers: [
      {
        name: "Name 1",
        age: "21",
        address: "Street 1",
        passportNo: "1234567890",
        ancillary: "Wheelchair",
        seat: 1,
        checkedIn: true,
        disabled: true,
        infant: false,
      },
      {
        name: "Name 2",
        age: "22",
        address: "Street 2",
        passportNo: "1234567891",
        ancillary: "None",
        seat: 2,
        checkedIn: true,
        disabled: false,
        infant: true,
      },
      {
        name: "Name 3",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 3,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 4",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 4,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 5",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 5,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 6",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 6,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 7",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 7,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 8",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 8,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 9",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 9,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 10",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 10,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 11",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 11,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 12",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 12,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 13",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 13,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 14",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 14,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 15",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 15,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 16",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 16,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 17",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 17,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 18",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 18,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 19",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 19,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 20",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 20,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 21",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 21,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 22",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 22,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 23",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 23,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 24",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 24,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 25",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 25,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 26",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 26,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 27",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 27,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 28",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 28,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 29",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 29,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 30",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 30,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 31",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 31,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 32",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 32,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 33",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 33,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 34",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 34,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 35",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 35,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 36",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 36,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 37",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 37,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 38",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 38,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 39",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 39,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
      {
        name: "Name 40",
        age: "25",
        address: "Bangalore",
        passportNo: "12356678",
        ancillary: "None",
        seat: 40,
        checkedIn: false,
        disabled: false,
        infant: false,
      },
    ],
  },
];
